### PR TITLE
debian: drop custom LTO handling

### PR DESCRIPTION
**Pull request by Saviq**

### CODE REVIEW

**Review by RAOF — APPROVED** [review]
Yup, reasonable

**Comment by RAOF** [comment]
We probably want to follow up to make sure that the mir-libs snap (and everything else) is doing the right thing.

**Comment by Saviq** [comment]
> We probably want to follow up to make sure that the mir-libs snap (and everything else) is doing the right thing.

I dropped the only other mentions of `MIR_LINK_TIME_OPTIMIZATION`, so we should be fine. Nothing in `mir-libs`, or everything else that should be affected.

**Comment by RAOF** [comment]
> > We probably want to follow up to make sure that the mir-libs snap (and everything else) is doing the right thing.
> 
> I dropped the only other mentions of `MIR_LINK_TIME_OPTIMIZATION`, so we should be fine. Nothing in `mir-libs`, or everything else that should be affected.

Oh, I meant to make sure that these places retain the benefit of LTO.

**Comment by Saviq** [comment]
> > > We probably want to follow up to make sure that the mir-libs snap (and everything else) is doing the right thing.
> 
> Oh, I meant to make sure that these places retain the benefit of LTO.

*cough*. They `mir-libs` does not have LTO enabled... but it being used in CI only, I wonder if it's appropriate anyway? I think we want to optimize more for build time than runtime performance here.

What "everything else" did you have in mind?

**Comment by RAOF** [comment]
> What "everything else" did you have in mind?

I… didn't, really. I guess: ensure the PPA builds have LTO? Is there anywhere else that we pull artifacts from, that *should* have LTO enabled?

**Comment by Saviq** [comment]
> ensure the PPA builds have LTO?

Wasn't the purpose to let the distro admins to decide? :shrug:
But yes, Ubuntu has it enabled by default - Debian, not so.

> Is there anywhere else that we pull artifacts from, that _should_ have LTO enabled?

Not that I know of.

This is good to go from my PoV.

**Comment by RAOF** [comment]
Good to go by me then, too.

**Pull request merged**
