### PR TITLE
spread: disable optimizations on newer toolchains

### PR DESCRIPTION
**Pull request by Saviq**
LTO is causing link failures again...

https://bugs.launchpad.net/ubuntu/+source/binutils/+bug/2070302

### CODE REVIEW

**Review by AlanGriffiths — APPROVED** [review]
Seems to work but is there an upstream bug we could tie it to?

**Comment by Saviq** [comment]
This now spread to `ubuntu_devel` and `_proposed`. Working on a bug report now.

**Review by AlanGriffiths — APPROVED** [review]
[holds nose]

**Comment by Saviq** [comment]
Sorry, just working on a slightly better approach.

**Comment by Saviq** [comment]
@AlanGriffiths OK, this should be good, builds also on LP at:
- https://launchpad.net/~mir-team/+archive/ubuntu/test-quirks/+packages
- https://launchpad.net/~mir-team/+archive/ubuntu/test-quirks-proposed/+packages

**Comment by Saviq** [comment]
The riscv64 builds in the PPAs are fixed by bringing this back:

https://github.com/canonical/mir/compare/ecf4344fff885b0cc019e8398a3772dc2725abbd..bab58c59d1e4cfd3d57beba3f9caf45a14fced26

**Review by AlanGriffiths — APPROVED** [review]
OK

**Pull request merged**
