### PR TITLE
Do not default window size

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Stop pretending (mostly) that windows we don't know the size of are 640x480, 100x100, or 1x1.

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Converted to draft until test failures are resolved

**Comment by AlanGriffiths** [comment]
@Saviq d715f563774a09453a892d105c17a7354d1d1f13 fixes some UB - is that worth a cherry-pick to 2.18.3?

**Comment by Saviq** [comment]
> @Saviq [d715f56](https://github.com/canonical/mir/commit/d715f563774a09453a892d105c17a7354d1d1f13) fixes some UB - is that worth a cherry-pick to 2.18.3?

Since we weren't planning to rebuild snaps based on 2.18.3, I don't think so.

**Comment by AlanGriffiths** [comment]
> Since we weren't planning to rebuild snaps based on 2.18.3, I don't think so.

NM, _this_ PR introduced the UB anyway, so irrelevant

**Review by tarek-y-ismail — CHANGES_REQUESTED** [review]
Looks good. Tested both bomber with miral-shell and kgx with miral-kiosk and they work as expected :+1: . Just need to rebase on main to get the docs checks to pass and we're all good to merge.

**Comment by AlanGriffiths** [comment]
> Just need to rebase on main to get the docs checks to pass and we're all good to merge.

AFAICS docs "pass" is not required for merge.

**Review by tarek-y-ismail — APPROVED** [review]

**Comment by tarek-y-ismail** [comment]
Yeah I'm working on those right now. I'm also not sure why the errors popped up now.

**Pull request merged**
