### PR TITLE
ci: symbols on LLVM 18

### PR DESCRIPTION
**Pull request by Saviq**
Alan's reporting this is fine on clang-18

### CODE REVIEW

**Review by mattkae — APPROVED** [review]
Yup! I suppose clang-18 supports c++23, so it shouldn't be a problem

**Comment by Saviq** [comment]
@mattkae didn't you have trouble with 18? Or was it just that we didn't have 18, and 19 was available in the LLVM archives?

**Review by AlanGriffiths — APPROVED** [review]
Cool

**Comment by mattkae** [comment]
> @mattkae didn't you have trouble with 18? Or was it just that we didn't have 18, and 19 was available in the LLVM archives?

19 was latest so I was just doing that. 18 is minimum :)

**Pull request merged**
