### PR TITLE
Live scale changes

### PR DESCRIPTION
**Pull request by AlanGriffiths**
Surfaces need to track scale changes on outputs they appear on

Fixes: #3552

(Reviewers note: this depends on #3586)

### CODE REVIEW

**Review by tarek-y-ismail — APPROVED** [review]

**Comment by AlanGriffiths** [comment]
@tarek-y-ismail your time is better spend reviewing things that are "ready for review". (This is "draft" for a reason: it breaks stuff - currently "leave" notifications.)

**Comment by tarek-y-ismail** [comment]
> @tarek-y-ismail your time is better spend reviewing things that are "ready for review". (This is "draft" for a reason: it breaks stuff - currently "leave" notifications.)

No worries, I was just curious and thankfully the PR was small so it didn't take much time to read through. It definitely revealed stuff that I didn't think about before when first implementing fractional scaling :)

**Review by tarek-y-ismail — APPROVED** [review]

**Review by hbatagelo — CHANGES_REQUESTED** [review]
Looks good and works as expected. I've made a few suggestions, mostly to ensure consistency with the use of east const. I would also recommend adding `const` where applicable (e.g. `fractional_scale`).

**Review by hbatagelo — APPROVED** [review]
LGTM

**Pull request merged**
