### PR TITLE
Release 2.16.4

### PR DESCRIPTION
**Pull request by mattkae**
## Release Notes
mir (2.16.4) UNRELEASED; urgency=medium

  * Bugfix release:
    - Ignoring zero length gamma curves for KMS outputs (Fixes: #3238)
    - Add hardware cursor support (Fixes: #3198)
    - Screenshots now respect clipping areas and rotated outputs (Fixes: #3236)
      (Fixes: #3259)
    - Fixed custom attributes propagation on outputs
      (Fixes: https://github.com/canonical/ubuntu-frame/issues/172)
    - Handle the Ubuntu 64-bit time_t apocalypse (Fixes: #3285)

### CODE REVIEW

**Comment by mattkae** [comment]
@RAOF : I implemented a test in WLCS that works in `main` but will _not_ be cherry-picked into this PR, as it would introduce an ABI change. How can I ignore it here? Or would I need to disable it in WLCS?

**Comment by Saviq** [comment]
You'll need this as well:
- https://github.com/canonical/mir/pull/3290

You can see the build status in:
https://launchpad.net/~mir-team/+archive/ubuntu/rc

**Comment by Saviq** [comment]
Oh and don't worry about the conflict, the way to deal with this is to merge locally and push to `main`. Don't want to push anything to `release/*` after tagging, as that will trigger another candidate build.

**Review by AlanGriffiths — CHANGES_REQUESTED** [review]
There are 14 commits, but only 5 fixes mentioned in the changelog, that seems wrong!  Obviously the changelog and build related changes (like #3257) do not need mention, but omitting 10 of 14 commits seems wrong.

On closer examination there fixes included than are mentioned in the changelog, e.g.: #3261, #3238, #3240 & #3278.

I need to be convinced that #3237 and #3220 justify inclusion in a bugfix release: they are extensive and change (admittedly deprecated) APIs. Ideally, bugfix releases should only include things that can be tested in isolation and with confidence the rest of the system is stable.

**Comment by mattkae** [comment]
> I need to be convinced that #3237 and #3220 justify inclusion in a bugfix release: they are extensive and change (admittedly deprecated) APIs. Ideally, bugfix releases should only include things that can be tested in isolation and with confidence the rest of the system is stable.

I can part with #3237, but #3220 is dear to my heart as it fixes all of the problems that I'm having on Nvidia for miracle-wm. Without it, miracle-wm doesn't function out of the box on all of my systems. I understand the change is extensive, but it felt like a good time to test if that's working across different systems.

**Comment by AlanGriffiths** [comment]
```
2024-03-28T13:52:46.3245631Z E: Tried to extract package, but file already exists. Exit...
```
WTF?

**Review by AlanGriffiths — APPROVED** [review]

**Comment by AlanGriffiths** [comment]
I'm running Miriway `edge/mir-pr3299` on the same configuration I encountered #3238 (to test that fix) and only the external output shows content. (However, the cursor is visible on both outputs.)

**Comment by AlanGriffiths** [comment]
# Testing ~rc13

Note: DO NOT use the `beta` channel for testing - that has an `~rc14` generated with additional commits before the latest "forced push".

Bugfix|Fix confirmed
--|--
#3238|@AlanGriffiths
#3198| 
#3236|
#3259| 
https://github.com/canonical/ubuntu-frame/issues/172|
#3278|

**Comment by AlanGriffiths** [comment]
# Testing ~rc13 (mark II)

Note: Because I force-pushed after dropping a commit and editing the changelog we're still at `~rc13`

Bugfix|Fix confirmed|Comment
--|--|--
#3238||
#3198||
#3236||
#3259| |
https://github.com/canonical/ubuntu-frame/issues/172||

**Comment by AlanGriffiths** [comment]
I've had to force a rebuild of Miriway/beta with ppa:mir-team/rc, but that's now up to date with this PR. (It works as expected)

**Review by AlanGriffiths — APPROVED** [review]

**Review by Saviq — APPROVED** [review]
@AlanGriffiths @mattkae #3300 is biting me on Pis, but I don't see any real problems, I'm +1 to tag v2.16.4

**Comment by mattkae** [comment]
Screenshot items have been confirmed :tada:

**Pull request merged**
