### PR TITLE
Fix linking for CMAKE_BUILD_TYPE=UBSanitize

### PR DESCRIPTION
**Pull request by AlanGriffiths**

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
Marking "no-merge" until we see if notifications are raised correctly by sanitize build.

Please feel free to approve anyway.

**Comment by gerboland** [comment]
Tests pass in my local Spread run. Waiting for Travis

**Comment by Saviq** [comment]
bors try

**Comment by Saviq** [comment]
bors r=gerboland

**Pull request merged**
