### PR TITLE
Release 2.18.2

### PR DESCRIPTION
**Pull request by Saviq**
>  Release 2.18.2
> 
>  Enhancements:
>  - #3614
>  - #3617
>  
>  Bugs fixed:
>   - #3601
>   - #3600
>   - #3592
>   - #3573
>   - #3494
>   - #3609
>   - #3610

### CODE REVIEW

**Comment by AlanGriffiths** [comment]
We should also consider these for cherry-pick:

* #3599 
* #3591 
* #3594

**Comment by Saviq** [comment]
> We should also consider these for cherry-pick:

Done.

**Comment by Saviq** [comment]
> I've run through the things that should be fixed. I think we can mark this ready

I'm just looking into the last issue floating about (X11 dialog sizing).

**Review by AlanGriffiths — APPROVED** [review]
Legit

**Pull request merged**
