### PR TITLE
Subsurface ordering

### LINKED ISSUE #2487: Allow WlSubsurfaces to be placed explicitly relative to hierarchy
Wayland has some protocols to handle the explicit placement of WlSubsurfaces:
- above or below siblings
- even above or below the parent surface

I've started implementing a change for the first use-case since, as far as I see, making it work with the parent surface would involve at least sneaking another dummy WlSurface in between. I believe even Weston does something similar to that.

The initial change is here. I've not opened a PR yet since I would like to get some input around the big picture before continuing with this. Details can still be talked about in a PR.

https://github.com/fredldotme/mir-experimental/commit/ed3c67e51fc3be9f368cfab56276b6a6394c28c3

### PR DESCRIPTION
**Pull request by wmww**
Attempt at implementing subsurface re-ordering. This should work but I have no way to test. The WLCS tests that failed before still fail, but I don't trust that they're correct. I'm not going to put more work into getting this merged at this time, but if anyone wants to push this feature through this might be a good starting point.

Possibly fixes #2487.

### CODE REVIEW

**Comment by fredldotme** [comment]
I will gladly take on the challenge. Depending on our plans in Ubuntu Touch this might mean either backporting & refining on top of Mir 1.8 or taking 2.0.

This is more or less a requirement for supporting proper stacking of surfaces in multi-window mode in Waydroid, the Android compatibility solution for GNU/Linux systems.

**Comment by Saviq** [comment]
Hi @fredldotme, got any updates on this?

**Comment by wmww** [comment]
Fixes #345.

**Comment by fredldotme** [comment]
Just came around to notify I intend to take a look as soon as my lunar dev environment on my M1 is properly functioning. The idea is to test Waydroid on that configuration soon since I wouldn't have to backport anything really.

**Comment by AlanGriffiths** [comment]
This has been around 9 months, but still "Some checks haven’t completed yet"!

I wonder why?

**Pull request closed without merging**
